---
title: Een drukknop gebruiken met een Raspberry Pi
hero_image: images/banner.png
description: Hoe sluit je een drukknop aan op je Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Een drukknop aansluiten

