title: Using a button with a Raspberry Pi
hero_image: images/banner.png
description: How to connect a button to your Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
interests: ""
technologies: ""
steps:
  - title: Connecting a button

