---
title: Usando un bot贸n con una Raspberry Pi
hero_image: images / banner.png
description: C贸mo conectar un bot贸n a tu Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Conectar un bot贸n

