---
title: Usando um botão com um Raspberry Pi
hero_image: images/banner.png
description: Como conectar um botão ao seu Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - title: Conectando um botão

