---
title: Utilitzar un interruptor amb la Raspberry Pi
hero_image: images/banner.png
description: Com connectar un interruptor a la teva Raspberry Pi
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: true
interests: ""
technologies: ""
steps:
  - 
    title: Connectar un interruptor

